@isTest
public class QuoteOrderPDFHandlerTest {
    @isTest
    static void testattachQuotePDFsToRelatedOrderWithPDFs(){
        //1. Load
        //insert Quote
        //insert Order
        //create PDF
        //link it to Quote
        //2. Test
        //call the QuoteOrderPDFHandler class
        //3. Assert
        //assert to check if we have any pdf in order record
    }
    
    @isTest
    static void testattachQuotePDFsToRelatedOrderWithNoPDFs(){
        //1. Load
        //insert Quote
        //insert Order
        //create PDF
        //link it to Quote
        //2. Test
        //call the QuoteOrderPDFHandler class
        //3. Assert
        //assert to confirm we dont have any pdf in order record
    }
}